name: Planet Tiles Generation CDK CD

on: 
    push:
      branches:
        - main
      paths:
        - 'tiles-generation/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      
      - name: Use Node.js
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3.0.0
        with:
          node-version: '16.x'
      
      - name: Install cdk-cli & cdk-lib
        run: |
          npm install -g aws-cdk
          cd tiles-generation/cdk
          npm install aws-cdk-lib

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Planet Raster Tiles CDK
        run: |
          cd tiles-generation/cdk
          cdk deploy \
          PlanetVectorTileGeneration \
          EmailSNSPlanetRasterTileGeneration \
          SlackSNSPlanetRasterTileGeneration \
          --context BUCKET=${{secrets.RASTER_TILES_BUCKET}} \
          --context EMAIL=${{secrets.EMAIL}} \
          --context SLACK=${{secrets.SLACK}} \
          --require-approval never

      - name: Deploy Planet Vector Tiles CDK
        run: |
          cd tiles-generation/cdk
          cdk deploy \
          PlanetVectorTileGeneration \
          EmailSNSPlanetVectorTileGeneration \
          SlackSNSPlanetVectorTileGeneration \
          --context BUCKET=${{secrets.VECTOR_TILES_BUKCET}} \
          --context EMAIL=${{secrets.EMAIL}} \
          --context SLACK=${{secrets.SLACK}} \
          --require-approval never
