name: Test Tiles Generation CDK CD

on:
    pull_request:
      branches:
        - main
      paths:
        - 'tiles-generation/**'

jobs:
  test-tiles-generation-cdk-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      
      - name: Install cdk-cli  & cdk-lib
        run: |
          cd tiles-generation/cdk
          npm install aws-cdk aws-cdk-lib

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Synth CDK
        run: |
          cd tiles-generation/cdk
          cdk synth TestTileGenerationStack --context TILE_S3_BUCKET=${{secrets.TILE_S3_BUCKET}}

      - name: Deploy CDK
        run: |
          cd tiles-generation/cdk
          cdk deploy TestTileGenerationStack --context TILE_S3_BUCKET=${{secrets.TILE_S3_BUCKET}} --outputs-file ./cdk-outputs.json --require-approval never

      - name: Run ECS task
        run: |
          ClusterName=`jq -r '.TestTileGenerationStack .ClusterName' tiles-generation/cdk/cdk-outputs.json`
          CapacityProviderName=`jq -r '.TestTileGenerationStack .CapacityProviderName' tiles-generation/cdk/cdk-outputs.json`
          TaskDefinitionArn=`jq -r '.TestTileGenerationStack .TaskDefinitionArn' tiles-generation/cdk/cdk-outputs.json`
          echo $ClusterName
          echo $CapacityProviderName
          echo $TaskDefinitionArn
          AWS_PAGER="" aws ecs run-task --cluster $ClusterName --task-definition $TaskDefinitionArn --capacity-provider-strategy capacityProvider=$CapacityProviderName
